# Generated by Django 5.1.1 on 2024-09-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubmissionForm',
            new_name='Submission',
        ),
    ]
