# Generated by Django 5.1.1 on 2024-09-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appBackend', '0004_remove_submission_ielts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='consent',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='declaration',
        ),
        migrations.AddField(
            model_name='submission',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='idFile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/id/'),
        ),
    ]
